version: "3.1"
services:
   iseclv1-agent:
      image: isecl-trustagent:latest
      build: .
      hostname: trustagent
      network_mode: host
      privileged: true

      environment:
         - TRUSTAGENT_DOCKER_HOST_MOUNT=/root/host_root

      secrets:
         - source: trustagent_env
           target: trustagent.env

      volumes:
         - tagent-config-volume:/opt/trustagent/configuration
         - tagent-logs-volume:/opt/trustagent/logs
         - /var/lib/tpm:/var/lib/tpm
         - /:/root/host_root

volumes:
   tagent-config-volume:
   tagent-logs-volume:

secrets:
   trustagent_env:
      file: trustagent.env